# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 813b42011302efdc4ba624768f10e4bc54295d524af3526d74ab471053f340fa258cb11d881b8c54d2bebafd2e77366783db291f29b243fda617ba5ff67502dd

test:
  secret_key_base: b2804a6e39e0905428c56a04f09bff8503fc995205aed51165969f7b2ce9a4b54621df4cd0cf41e791abf8fcac5184797952ad1d27f42c76d9388f2c7e8ecffa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
